version: "3.7"

services:
  workspace:
    build:
      dockerfile: container/Dockerfile
      context: ./
    command:
      - tail
      - -f
      - /dev/null
    volumes:
      - ./:/workspace/:delegated
