version: "3.7"

services:
  dev:
    build:
      dockerfile: container/Dockerfile
      context: ./
      target: base
    command:
      - tail
      - -f
      - /dev/null
    volumes:
      - ./src:/workspace/src:cached
